name: Run tests and upload coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run Ruff linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff lint
        uses: chartboost/ruff-action@v1
        with:
          version: "0.9.9"
          args: check .

      - name: Run Ruff format
        uses: chartboost/ruff-action@v1
        with:
          version: "0.9.9"
          args: format --check .

  uv-lock-check:
    name: Check if uv.lock is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check if uv.lock is in sync with pyproject.toml
        run: uv lock --check

  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.11

      - name: Install the project dependencies
        run: uv sync

      - name: Download integrated dataset and run tests
        run: |
          uv run python scripts/download/movielens.py --package "ml-1m"
          uv run python scripts/download/movielens.py --package "ml-10m"
          uv run python scripts/download/pinterest.py
          ls recommender/.data/movielens
          ls recommender/.data/pinterest
          uv run pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
