name: Run tests and upload coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - name: View poetry --help
        run: |
          poetry --help
          poetry --version
          python --version

#      - name: Install dependencies
#        run: pip install -r requirements.txt
#
#      - name: Download ml-1m dataset and run tests
#        run: |
#          python recommender/preprocess/movielens/download.py --path ".movielens" --package "ml-1m"
#          ls recommender/preprocess/movielens/.movielens
#          pytest --cov --cov-report=xml
#
#      - name: Upload results to Codecov
#        uses: codecov/codecov-action@v4
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}