name: Run tests and upload coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install

      - name: Download ml-1m dataset and run tests
        run: |
          poetry run python recommender/preprocess/movielens/download.py --path ".movielens" --package "ml-1m"
          ls recommender/preprocess/movielens/.movielens
          poetry run pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}